[package]
name = "svn-hook"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "2.33"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
dirs = "4.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0" 